/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.meetupapp.api.autocomplete;

public class Matched_substringElement {
	private Integer length;

 	public void setLength(Integer length) {
		this.length = length;
	}

	public Integer getLength() {
		return length;
	}

	private Integer offset;

 	public void setOffset(Integer offset) {
		this.offset = offset;
	}

	public Integer getOffset() {
		return offset;
	}

}