/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.meetupapp.api.autocomplete;

public class PredictionElement {
	private String[] types;

 	public void setTypes(String[] types) {
		this.types = types;
	}

	public String[] getTypes() {
		return types;
	}

	private String reference;

 	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getReference() {
		return reference;
	}

	private TermElement[] terms;

 	public void setTerms(TermElement[] terms) {
		this.terms = terms;
	}

	public TermElement[] getTerms() {
		return terms;
	}

	private String place_id;

 	public void setPlace_id(String place_id) {
		this.place_id = place_id;
	}

	public String getPlace_id() {
		return place_id;
	}

	private String id;

 	public void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	private Matched_substringElement[] matched_substrings;

 	public void setMatched_substrings(Matched_substringElement[] matched_substrings) {
		this.matched_substrings = matched_substrings;
	}

	public Matched_substringElement[] getMatched_substrings() {
		return matched_substrings;
	}

	private String description;

 	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

}