/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.meetupapp.api.autocomplete;

public class TermElement {
	private String value;

 	public void setValue(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	private Integer offset;

 	public void setOffset(Integer offset) {
		this.offset = offset;
	}

	public Integer getOffset() {
		return offset;
	}

}