/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.snapdeal.springmvc.map.api.autocomplete;

public class AutoCompleteResponse {

	private PredictionElement[] predictions;

 	public void setPredictions(PredictionElement[] predictions) {
		this.predictions = predictions;
	}

	public PredictionElement[] getPredictions() {
		return predictions;
	}

	private String status;

 	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

}