/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.meetupapp.api.distanceMatrix;

public class DistanceMatrixResponse {

	private RowElement[] rows;
	private Integer value;
	private String text;
	private String status;
	private String[] destination_addresses;

 	public void setRows(RowElement[] rows) {
		this.rows = rows;
	}

	public RowElement[] getRows() {
		return rows;
	}

 	public void setValue(Integer value) {
		this.value = value;
	}

	public Integer getValue() {
		return value;
	}


 	public void setText(String text) {
		this.text = text;
	}

	public String getText() {
		return text;
	}

 	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}


 	public void setDestination_addresses(String[] destination_addresses) {
		this.destination_addresses = destination_addresses;
	}

	public String[] getDestination_addresses() {
		return destination_addresses;
	}

	private String[] origin_addresses;

 	public void setOrigin_addresses(String[] origin_addresses) {
		this.origin_addresses = origin_addresses;
	}

	public String[] getOrigin_addresses() {
		return origin_addresses;
	}

}