/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.snapdeal.springmvc.map.api.distanceMatrix;

public class Duration {
	private Integer value;

	private String text;

	public void setValue(Integer value) {
		this.value = value;
	}

	public Integer getValue() {
		return value;
	}



 	public void setText(String text) {
		this.text = text;
	}

	public String getText() {
		return text;
	}

}