/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.snapdeal.springmvc.map.api.distanceMatrix;

public class ElementElement {

	private DistanceMatrixResponse distance;
	private Duration duration;
	private String status;


 	public void setDistance(DistanceMatrixResponse distance) {
		this.distance = distance;
	}

	public DistanceMatrixResponse getDistance() {
		return distance;
	}



 	public void setDuration(Duration duration) {
		this.duration = duration;
	}

	public Duration getDuration() {
		return duration;
	}



 	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

}